jobs:
  - name: data_cleaning
    stages:
      # - name: "clean-base-tables"
      #   tasks:
      #     - name: "product"
      #       params: {}
      #     - name: "orders"
      #       params: {}

      # - name: "clean-derivative-tables"
      #   tasks:
      #     - name: "sales"
      #       params: {}
      - name: "housing-clean-base-tables"
        tasks:
          - name: "housing"
            params: {}
      - name: "housing-train-test-split"
        tasks:
          - name: "train_test"
            params:
              target: median_house_value
              test_size: 0.2

  - name: feat_engg
    stages:
      - name: "housing-feature-pipelines"
        tasks:
          - name: "transform_features"
            params:
              outliers:
                method: mean
                drop: False
              sampling_fraction: 0.1

  - name: model_gen
    stages:
      - name: "housing-model-creation"
        tasks:
          - name: "train_model"
            params:
              sampling_fraction: 0.1
              search_space:
                alpha: [0.001, 1]
                l1_ratio: [0, 1]
              random_seed: 42
              n_trials: 50
              n_jobs: -1
              cv: 5

  - name: model_eval
    stages:
      - name: "housing-model-predict"
        tasks:
          - name: "score_model"
            params: {}
